language: python
before_install:
  - sudo apt update
  - sudo apt install dwgsim
    # Install stuff for compiling cyvcf3
  - sudo apt install libssl-dev zlib1g-dev libcurl4-openssl-dev libbz2-dev liblzma-dev
  - pip install tox
  - pip install cython
dist: xenial
python: 3.6  # Use the oldest supported version of python as default.
script:
    - tox -e $TOX_ENV
matrix:
  include:
    # TEST LINTING
    # Use default python3 version here.
    - env: TOX_ENV=lint

    # UNIT TESTS
    # On most recent versions of python.
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.8
      env: TOX_ENV=py38
    - python: 3.6
      env: TOX_ENV=py36
      install:
        - pip install codecov
      after_success:
        # Correct coverage xml for coverage services.
        - >
          bash -c 'set -eux;
          pkg_path=$(find .tox/py*/lib/python*/site-packages/biotdg -maxdepth 0 -type d);
          sed -i "s:${pkg_path}:src/biotdg:g" coverage.xml'
        - codecov -v  # -v to make sure coverage upload works.
